import React from 'react';
import CssBaseline from '@mui/material/CssBaseline';
import Header from '../components/Header';
import Footer from '../components/Footer';
import { Typography } from '@mui/material';

export default function MainPage() {
  return (
    <>
      <CssBaseline />
        <Header />
        <Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography><Typography>
          asd
        </Typography>
        <Footer />
    </>
  );
}